# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem"s dependencies in ft_wikipedia.gemspec
gemspec

gem "rake", "~> 13.0"

gem "minitest", "~> 5.0"
gem "nokogiri", "~> 1.11", ">= 1.11.6"
gem "open-uri", "~> 0.1.0"
